### ISSUE TITLE
Vaultwarden API Error

### ISSUE THREAD

**Issue by th3voic3** [TheManchineel/vaultwarden-api#2]
Hi,

I set this up in Portainer like so:
```
version: '3'

services:
  vaultwarden-api:
    image: ghcr.io/themanchineel/vaultwarden-api:main
    container_name: vaultwarden-api
    restart: always
    ports:
      - 8019:8019
    env_file: stack.env
```

The environment variables are all setup.

When testing with curl I get:
curl "http://localhost:8019/api/stats" -H 'X-API-Key: [APIKEY]'
{"detail":"Vaultwarden API error"}

The logs show this:
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8019 (Press CTRL+C to quit)
INFO:     10.0.6.1:11059 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
INFO:     10.0.6.1:36873 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
INFO:     172.16.176.1:36006 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
INFO:     10.0.6.1:36912 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
INFO:     172.16.176.1:34382 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
INFO:     10.0.6.1:36938 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
INFO:     10.0.6.1:37044 - "GET /api/stats HTTP/1.1" 500 Internal Server Error
```

Any idea what's wrong?

Thank you for your work on this, this is great!

**Comment by t3chguy** [comment]
I'm seeing the same failure mode. Following the debug from https://github.com/TheManchineel/vaultwarden-api/issues/1#issuecomment-1875969178 I successfully get the `VW_ADMIN` token;

```
>>> print(response.status_code)
200
>>> print(response.cookies["VW_ADMIN"])
eyJ0eXLCJhbGciOiJSUz.eyJuYmYiOjE3MDQ1NzE0CI6MTcwNDU3MjY5NSwiaX...
```

but get 500's trying to use this project

![image](https://github.com/TheManchineel/vaultwarden-api/assets/2403652/50089f88-f8cd-4120-8fed-7f7c3c920439)

**Comment by t3chguy** [comment]
Having forked and added a print to the exception:

![image](https://github.com/TheManchineel/vaultwarden-api/assets/2403652/cd91da1f-aa9c-43c2-b5f1-4da3fbe3e033)

**Comment by t3chguy** [comment]
![image](https://github.com/TheManchineel/vaultwarden-api/assets/2403652/afe8a1ab-b99d-4390-90c7-8c40b3e623b9)

https://github.com/t3chguy/vaultwarden-api/commit/1083b62ce515c5ce753befc6b5fe32d1c3a76f69 fixed it for me. Others can try it by using `ghcr.io/t3chguy/vaultwarden-api:main`

**Comment by TheManchineel** [comment]
This is all merged, plus now I added support to accommodate both timezone formats (timezone name and offset). I had no idea that part of the response was platform specific (not like viewing that data is implemented functionality at all, at the moment, lol). Thanks @t3chguy for the fix!

**Comment by t3chguy** [comment]
Thanks @TheManchineel for your reddit post which helped me get into Homepage! (and this repo obvs)

![image](https://github.com/TheManchineel/vaultwarden-api/assets/2403652/95974fc1-1528-404a-96b8-01d8c6f5c54a)
